#pragma once
#include "AlpoSprite.h"
class __declspec(dllimport) CharacterSprite : public AlpoSprite {
public:
	unsigned int vars[38];
	virtual void GenerateNewGoal(void);
	virtual bool MaybeAddPauseGoal(int);
	virtual void CleanUpAfterPreviousGoal(void);
	virtual void FilterGoal(int, int*, AlpoSprite*, AlpoSprite*);
	virtual int GetOverallEmotionValue(int) const;
	virtual Personality* GetPersonality(void) const;
	virtual pfvector<XBrain, char const*>& GetBiorhythms(void);
	virtual void DispatchGoals(int, GoalToken&);
	virtual void DispatchPlans(PlanToken&);
	virtual void DispatchEmotions(EmotionToken&);
	virtual char const* GetGoalStringName(int) const;
	virtual char const* GetPlanStringName(int) const;
	virtual char const* GetEmotionStringName(int) const;
	virtual int GetMaxPetEmotionName(void) const;
	virtual bool AreWeAsleep(void) const;
	virtual int GetDistanceToSprite1(AlpoSprite*) const;
	virtual XTPoint<int> GetSpriteLocation1(AlpoSprite*) const;
	virtual int GetAngleBetweenSprites2(AlpoSprite*, AlpoSprite*) const;
	virtual int GetDistanceFromPointToSprite2(XTPoint<int>, AlpoSprite*) const;
	virtual int GetSpriteSpeed1(AlpoSprite*) const;
	virtual XTRect<int, long> GetSpriteDrawRect1(AlpoSprite*) const;
	virtual bool IsSpriteBeingHeldByAPetOrMouse1(AlpoSprite*) const;
	virtual bool IsSpriteBeingHeldByCursor1(AlpoSprite*) const;
	virtual bool IsSpriteBeingHeldBySprite2(AlpoSprite*, AlpoSprite*) const;
	virtual bool IsSpriteBeingHeldByThisPetOrMouse2(AlpoSprite*, AlpoSprite*) const;
	virtual AlpoSprite* GetSpriteHoldingSprite1(AlpoSprite*) const;
	virtual AlpoSprite* GetWhatThisSpriteIsHolding1(AlpoSprite*) const;
	virtual int GetSecondsSinceFrame(long) const;
	virtual bool IsSpriteInShelf1(AlpoSprite*) const;
	virtual bool IsShelfMinimized0(void) const;
	virtual bool IsShelfHere0(void) const;
	virtual bool IsSpriteJuxtaposedWithShelf1(AlpoSprite*, bool);
	virtual bool IsSpriteInContainer1(AlpoSprite*) const;
	virtual bool IsSpriteInStrongContainer1(AlpoSprite*) const;
	virtual bool IsSpriteInThisContainer2(AlpoSprite*, AlpoSprite*) const;
	virtual bool IsSpriteAboveHorizon1(AlpoSprite*) const;
	virtual bool IsPointAboveHorizon1(XTPoint<int>) const;
	virtual bool AmIAttachedToSprite1(AlpoSprite*) const;
	virtual bool AmIOverlappingWithSprite1(AlpoSprite*) const;
	virtual int GetSpriteRotation1(AlpoSprite*) const;
	virtual void GetGoalInfo5(AlpoSprite*, int*, int*, AlpoSprite**, AlpoSprite**) const;
	virtual int PtToPtAngle(XTPoint<int>*, XTPoint<int>*) const;
	virtual AlpoSprite* MyGet1AlpoByAdj(bool, AlpoSprite*, ...) const;
	virtual int GetAllToys(bool, AlpoSprite*, pfvector<XTSmartPtr<AlpoSprite*>, char const*>&, bool, bool);
	virtual ScriptDialogState GetScriptDialogState(void) const;
	virtual bool IsSafeToAttachSprite(AlpoSprite*, int, int) const;
	virtual bool IsPositionSafeToAttachSprite(AlpoSprite*, int, int) const;
	virtual void AttachSprite(AlpoSprite*, int, E3DToyAttach, int, AlpoSprite*, bool, EStackMode);
	virtual bool CanIPounce(void) const;
	virtual bool CanISnagHang(void) const;
	virtual void DetachSprites(int, int);
	virtual void EnterBackyard(void);
	virtual void LookAtRandomPoint(void);
	virtual void LookForward(void);
	virtual void LookAtUser(void);
	virtual void ResetEyelids(void);
	virtual void EyesNormal(void);
	virtual void EyesClosed(void);
	virtual void EyesWideOpen(void);
	virtual void EyesSad(void);
	virtual void EyesMean(void);
	virtual void EyesPleased(void);
	virtual void EyesTired(void);
	virtual void GetOrientationInfo(int, XTPoint<int>*, AlpoSprite*, XTPoint<int>*, FacingDirection*, XTPoint<int>*);
	virtual bool ArePointsTooFarApart(XTPoint<int>, XTPoint<int>, int) const;
	virtual XTPoint<int> GetAndrewFuturePoint(int, XTPoint<int>, XTPoint<int>);
	virtual XTPoint<int> ProjectPointGivenRotation(XTPoint<int>, int, XTPoint<int>, bool);
	virtual bool AreWeNearPetDoor(void) const;
	virtual bool GetStrongestTerritoryMarking(XTPoint<int>*);
	virtual void SetTerritoryMarking(XTPoint<int>, int);
	virtual AlpoSprite* GetHoleToBuryInto(void);
	virtual AlpoSprite* GetHoleToDigUp(void);
	virtual AlpoSprite* GetBasketNearby(void);
	virtual AlpoSprite* GetNewSSProp(void);
	virtual void ReturnSSProp(void);
	virtual bool IsUserHoldingBrush(void) const;
	virtual AlpoSprite* GetPillowWeWereDroppedOn(void);
	virtual int MapBiorhythmToRange(PetBiorhythm, int, int);
	virtual int MapTraitToRange(BehaviorTrait, int, int);
	virtual int GetTraitValue2(CharacterSprite const*, BehaviorTrait);
	virtual void IncrementTraitValue3(CharacterSprite const*, BehaviorTrait, int);
	virtual void DecrementTraitValue3(CharacterSprite const*, BehaviorTrait, int);
	virtual bool GetOtherPetSprites(pfvector<XTSmartPtr<CharacterSprite*>, char const*>&, EChrz) const;
	virtual bool GetOtherSuitablePet(XTSmartPtr<CharacterSprite*>&, EChrz) const;
	virtual LookMode GetFreeToAutoLook(void) const;
	virtual bool GetFreeToAutoMood(void) const;
	virtual bool GetFreeToAutoTalk(void) const;
	virtual bool IsMicOn(void) const;
	virtual XSprite* GetSpritePtrFromGenericType(EScriptSpriteToken token) const override;
	virtual bool GetIsChrz() const override;
	virtual void DoPhysics(void) override;
	virtual ~CharacterSprite();
};