#pragma once
#include "CharacterSprite.h"
#include "StateMachine.h"
class __declspec(dllimport) PetSprite : public CharacterSprite, public StateMachine {
public:
	unsigned int vars[944];
	virtual void AddBreedSpecificGoal(void);
	virtual void InitBreedSprite(LoadInfo const&, bool) = 0;
	virtual void InitBreedSprite(LoadInfo const&, char*, bool, bool) = 0;
	virtual void InitPersonalityBiorhythms(void) = 0;
	virtual bool GetIsFullyInitialized(void) const;
	virtual void CreateHeadShot(ColorTypes);
	virtual Filmstrip& GetCaseIcon(void) const;
	virtual Filmstrip& GetAdptIcon(void) const;
	virtual bool GetIsNewborn(void) const;
	virtual bool GetIsInfant(void) const;
	virtual bool GetIsJuvenile(void) const;
	virtual bool GetIsAdult(void) const;
	virtual bool GetIsAtBreedableAge(void) const;
	virtual int GetSwatCone(bool) const;
	virtual void DoDownloadPreBreeding(LnzInfo&, XPhenotype&, PetSprite const&) const;
	virtual bool DoDownloadBreeding(LnzInfo&, XPhenotype&, PetSprite const&) const;
	virtual void FixupTrait(ETrait, XPhenotype&) const;
	virtual void ConstructGenome(Genome&);
	virtual bool PopScript(int*);
	virtual void SnagHangDraw(void);
	virtual void SetupPounce(void);
	virtual BasketPeekType GetInitialBasketPeekType(AlpoSprite*);
	virtual AlpoSprite* GetOtherPetInBasket(AlpoSprite*);
	virtual void ForcePetInBasket(AlpoSprite*);
	virtual void DoBasketAnimation(bool);
	virtual void DoBasketClipping(bool);
	virtual void CleanUpAfterCatFighting(bool);
	virtual UAction MapCatFighterMasterToSlave(PetSprite*);
	virtual UAction GetCatFighterAction(void);
	virtual XTPoint<int> GetBounceDockPoint(AlpoSprite*, int);
	virtual void InitDramaManager(void);
	virtual void IngestSprite(AlpoSprite*);
	virtual void PetJustAteSomething(AlpoSprite*);
	virtual bool MeetFoodFinickinessRequirement(AlpoSprite*);
	virtual AlpoSprite* FindSomethingToEat(void);
	virtual bool AmITooCloseToSprite(AlpoSprite*);
	virtual bool IfOffscreenThenAnimateOnscreen(void);
	virtual void ResumeAfterHeld(bool);
	virtual void HandleBlinking(void);
	virtual void HandleMiscEnvironment(void);
	virtual void HandleCaseZSort(void);
	virtual void HandleBiorhythms(void);
	virtual void HandleUserTugging(void);
	virtual void HandlePetting(void);
	virtual void HandleSpriteDestroyed(AlpoSprite*, short);
	virtual void HandleMiscLayering(void);
	virtual void HandleCatnipped(bool);
	virtual XTPoint<int> GetHandBorderPoint(void);
	virtual void SetHandBorderPoint(XTPoint<int>, int, int);
	virtual bool ComputeJumpDownPoint(XTPoint<int>&);
	virtual void HandleLedgeMoveDuringJump(void);
	virtual void HandleLedgeMoveWhenOnLedge(void);
	virtual void SetupForJump(int*, int*, PetState*);
	virtual void PutUtilityAtJumpOnEdge(XTSmartPtr<Ledge*> const&, EdgeName);
	virtual EdgeName PutUtilityAtClosestEdge(void);
	virtual XTRect<int,long> GetJumpOnSpriteRect(AlpoSprite*, EdgeName);
	virtual bool CanWeClimbInThisDirection(int);
	virtual ScreenArea GetSpriteScreenArea(AlpoSprite*);
	virtual bool IsLocomotionTargetReached(AlpoSprite*);
	virtual bool GetOnscreenIfNeeded(XTPoint<int>*);
	virtual void TargetACornerToAvoidSprite(AlpoSprite*, XTPoint<int>*);
	virtual void BumpAnyToys(void);
	virtual bool CheckForCustomLocomoteConditions(void);
	virtual int GetNumFramesInJumpOrSkid(UAction);
	virtual bool ComputeCatchToyStuff(XTPoint<int>, XTPoint<int>, UAction*, XTPoint<int>*, UAction);
	virtual bool CheckForBlendAlign(void);
	virtual XTPoint<int> GetMyLocomoteFuturePt(int);
	virtual void StartLocomotionLayering(UAction);
	virtual void StopLocomotionLayering(void);
	virtual void DoLocomoteHeadTracking(int);
	virtual UAction GetPostureLayerToDo(void);
	virtual bool AmILoyalToSomeoneElse(PetSprite*);
	virtual bool AmIFertile(void);
	virtual bool AreWeDestinedToBeInLove(PetSprite*);
	virtual bool GetFreeLoveMode(PetSprite*);
	virtual int GetMyCompatibilityWithYou(PetSprite*);
	virtual int GetOurCombinedCompatibility(PetSprite*);
	virtual bool MutualHorniness(PetSprite*);
	virtual bool AreWeIncestuous(PetSprite*);
	virtual bool AreEitherOfUsParents(PetSprite*);
	virtual int GetCourtshipRate(PetSprite*);
	virtual void ModifyCourtshipStage(PetSprite*, bool);
	virtual long ComputeMatchmakerID(void);
	virtual bool AmIYourFather(PetSprite*);
	virtual bool AmIYourMother(PetSprite*);
	virtual bool AmIYourSibling(PetSprite*);
	virtual UAction GetNipperAction(void);
	virtual void CleanUpAfterNipping(bool);
	virtual UAction MapNipperMasterToSlave(PetSprite*);
	virtual void InitPettingModes(void);
	virtual int WhichBallBeingPet(void);
	virtual void DefuzzPet(void);
	virtual void PetRegionSwitch(PettingRegion);
	virtual void SetPettingMode(PettingMode);
	virtual PettingMode GetPettingModeHistory(int);
	virtual bool IsPetGettingMoreIntimate(void);
	virtual PettingRegion WhichRegionBeingPet(void);
	virtual int GetCursorMovement(void);
	virtual bool HasUserStoppedPetting(void);
	virtual void CleanUpAfterPetting(void);
	virtual PetReaction GetBadPetReaction(void);
	virtual void UpdatePettingCursor(void);
	virtual void UpdatePettingFuzz(void);
	virtual bool CanGoToSleepAfterPetting(void);
	virtual bool AmIPetting(void);
	virtual void HandleSocialAwareness(void);
	virtual void StopAnySocialDiversion(void);
	virtual void ResumeSocialDiversion(void);
	virtual long GetFrameLastNoticed(short);
	virtual void SetFrameLastNoticed(short, long);
	virtual void InfectOthers(bool);
	virtual int GetSwatMissDistance(void);
	virtual TargetHeight GetTargetHeight(AlpoSprite*, int);
	virtual void TuggeeBecomesTugger(AlpoSprite*);
	virtual void CleanUpAfterTugging(bool);
	virtual void TuggeeDraw(AlpoSprite*);
	virtual void EndUserTugToyTugging(void);
	virtual void HandleVoiceRecognition(void);
	virtual void ReactToVoiceInterpretation(WordConceptIndex);
	virtual void CleanUpAfterWrestling(bool);
	virtual UAction MapWrestlerMasterToSlave(PetSprite*);
	virtual UAction MapWrestlerSlaveToMaster(PetSprite*);
	virtual UAction GetWrestlerAction(void);
	virtual void BeContactedBySprite4(AlpoSprite*, int, UAction, bool);
	virtual void BeOnLedge1(XTSmartPtr<Ledge*> const&);
	virtual void BePaintedBySprite1(AlpoSprite*);
	virtual void BeSprayedBySprite3(AlpoSprite*, UAction, bool);
	virtual void BlendDockToSprite1(AlpoSprite*);
	virtual void BounceContactDockToSprite2(AlpoSprite*, UAction);
	virtual void BounceDockToSprite2(AlpoSprite*, int);
	virtual void BounceDockToSpriteHeldBySprite2(AlpoSprite*, AlpoSprite*);
	virtual void BounceToRotation1(int);
	virtual void CarryPetDockToPet1(AlpoSprite*);
	virtual void CatFight2(AlpoSprite*, bool);
	virtual void CatMoment0(void);
	virtual void CatStalkSprite1(AlpoSprite*);
	virtual void Conceive2(UAction, AlpoSprite*);
	virtual void CrawlToSprite1(AlpoSprite*);
	virtual void DropSprite2(UAction, AlpoSprite*);
	virtual void EatCapturedSprite0(void);
	virtual void EatDrinkFromBowl1(AlpoSprite*);
	virtual void EatFromHand0(void);
	virtual void EnterPetDoor0(void);
	virtual void EyeTrackSprite1(AlpoSprite*);
	virtual void GimmeSpace0(void);
	virtual void InBasket3(AlpoSprite*, bool, bool);
	virtual void JumpOnAndRideSprite1(AlpoSprite*);
	virtual void JumpToCeiling1(AlpoSprite*);
	virtual void JumpToClosestEdgeAndClimb0(void);
	virtual void JumpToEdgeAndClimb2(EdgeName, bool);
	virtual void JumpToLedge2(XTSmartPtr<Ledge*> const&, EdgeName);
	virtual void JumpToSpriteLedge2(AlpoSprite*, EdgeName);
	virtual void LeanOnLedge2(XTSmartPtr<Ledge*> const&, AlpoSprite*);
	virtual void LocomoteToPoint2(int, int);
	virtual void LocomoteToSprite1(AlpoSprite*);
	virtual void LookAroundAtToys1(UAction);
	virtual void LookAtSprite1(AlpoSprite*);
	virtual void LookAtUserEarCock(void);
	virtual void MountSprite1(AlpoSprite*);
	virtual void NipAtPet2(AlpoSprite*, bool);
	virtual void PickUpSprite4(AlpoSprite*, UAction, AlpoSprite*, bool);
	virtual void PlayCatAction4(int, bool, AlpoSprite*, AlpoSprite*);
	virtual void PlayDogAction4(int, bool, AlpoSprite*, AlpoSprite*);
	virtual void PlayDogSleepWalkAction4(int, bool, AlpoSprite*, AlpoSprite*);
	virtual void PlayUAction4(UAction, bool, AlpoSprite*, AlpoSprite*, bool);
	virtual void PlayMaltoUAction4(UAction, UAction, bool, AlpoSprite*);
	virtual void PounceOnSprite1(AlpoSprite*);
	virtual void PreStalkSprite1(AlpoSprite*);
	virtual void RegrabSprite1(AlpoSprite*);
	virtual void RideOnSprite1(AlpoSprite*);
	virtual void SitOnSpriteLedge1(AlpoSprite*);
	virtual void SkidorJumpDockToSprite2(AlpoSprite*, UAction);
	virtual void SnagPounceOnSprite1(AlpoSprite*);
	virtual void StealToyFromSprite1(AlpoSprite*);
	virtual void SuckleSprite1(AlpoSprite*);
	virtual void SwatSprite1(AlpoSprite*);
	virtual void ThrowSprite1(UAction);
	virtual void TossSpriteWithPet2(AlpoSprite*, AlpoSprite*);
	virtual void TugOfWarWithSprite1(AlpoSprite*);
	virtual void UserTugSprite1(AlpoSprite*);
	virtual void WaitAndWatchSprite3(AlpoSprite*, UAction, bool);
	virtual void WrestlePet2(AlpoSprite*, bool);
	virtual PetState GetPetCurrentState1(AlpoSprite*) const;
	virtual int GetPetBiorhythm2(AlpoSprite const*, PetBiorhythm) const;
	virtual void SetPetBiorhythm3(AlpoSprite*, PetBiorhythm, int) const;
	virtual void IncrementPetBiorhythm3(AlpoSprite*, PetBiorhythm, int) const;
	virtual void SetPetIAmCarrying(PetSprite*);
	virtual PetSprite* GetPetIAmCarrying(void) const;
	virtual void ResetLocomoteVariables0(void);
	virtual void ResetDockingVariables0(void);
	virtual void ResetPickUpVariables0(void);
	virtual EdgeName TryToTargetAnEdge6(EdgeName, bool, XTPoint<int>*, int*, int*, XTSmartPtr<Ledge*> const&);
	virtual void PotatoBug2(int, int);
	virtual int CountHoardedObjects(XTPoint<int>);
	virtual void SnootyNose(void);
	virtual bool AmINeverAfraid(void);
	virtual void GetSpriteRelationship(AlpoSprite*, RelationshipType&, bool);
	virtual void SetFreshPetAffinity(PetSprite*);
	virtual AlpoSprite* GetFavoriteToy(void);
	virtual void PrintRelationships(void);
	virtual void PrintPhenotype(void);
	virtual void EmotionHappy(EmotionToken&);
	virtual void EmotionSad(EmotionToken&);
	virtual void EmotionAnger(EmotionToken&);
	virtual void EmotionFear(EmotionToken&);
	virtual void EmotionCrave(EmotionToken&);
	virtual void EmotionJealous(EmotionToken&);
	virtual void EmotionShame(EmotionToken&);
	virtual void PushEvent(EventName, AlpoSprite*, AlpoSprite*);
	virtual void HandleEvents(void);
	virtual bool IsThisATrainableTreat(AlpoSprite*);
	virtual bool HandleOnLedge(EventToken&);
	virtual void EventAphrodisiac(EventToken&, int);
	virtual void EventBackgroundChange(EventToken&, int);
	virtual void EventCamera(EventToken&, int);
	virtual void EventClothed(EventToken&, int);
	virtual void EventCursor(EventToken&, int);
	virtual void EventDisciplineToy(EventToken&, int);
	virtual void EventIngested(EventToken&, int);
	virtual void EventLedgesRemoved(EventToken&, int);
	virtual void EventLoudNoise(EventToken&, int);
	virtual void EventMedicine(EventToken&, int);
	virtual void EventOverDisciplined(EventToken&, int);
	virtual void EventPaint(EventToken&, int);
	virtual void EventPet(EventToken&, int);
	virtual void EventTreat(EventToken&, int);
	virtual void EventUnfamiliarSprite(EventToken&, int);
	virtual void EventVoiceCommand(EventToken&, int);
	virtual void EventWateringCan(EventToken&, int);
	virtual bool AlreadyInvolvedWith(AlpoSprite*, EventName, bool);
	virtual bool IsPetInAnAlignmentGoal(PetSprite*);
	virtual bool AmIOKToDoStuff(void);
	virtual void GotPlayedWith(void);
	virtual bool IFeelOKAbout(AlpoSprite*);
	virtual bool IFeelFinickyAbout(AlpoSprite*);
	virtual int ChanceOfInteractingWithNearbyPet(void);
	virtual void SetNeglectedThresholds(void);
	virtual void RunGoalDiagnostics(void);
	virtual PetGoalName MapGoal(PetGoalName) const;
	virtual PetPlanName MapPlan(PetPlanName) const;
	virtual PetState MapState(PetState) const;
	virtual void StandardFaceToFaceGoalLogic(GoalToken&, UAction, UAction, int);
	virtual void SetupFaceToFaceMaltoscript(GoalToken&, int, EventName, int);
	virtual void StartFaceToFaceMaltoscript(GoalToken&, UAction, UAction);
	virtual int MCIFilter(int, CharacterSprite&, GoalSearchContext, EventName, int&, XTSmartPtr<AlpoSprite*>&, XTSmartPtr<AlpoSprite*>&, int&, int&, int&, RelationshipRange, EventName);
	virtual bool MatchRelationships(XTSmartPtr<AlpoSprite*>&, RelationshipRange, bool);
	virtual bool MatchRelationshipRangeCheck(RelationshipRange, bool);
	virtual void MakeVocalSound(AlpoSprite*);
	virtual void MapAndPlayPetSound(PetSoundType);
	virtual UAction MapPetSound(PetSoundType);
	virtual void SetPurring(PurrLevel);
	virtual AlpoSprite* FindABouncyBallishProp(void);
	virtual AlpoSprite* FindAFetchProp(void);
	virtual AlpoSprite* FindAFoodProp(void);
	virtual AlpoSprite* FindBouncyBallishPropNearSprite(AlpoSprite*);
	virtual AlpoSprite* GenericFindToyMatch(Match const&, bool);
	virtual AlpoSprite* GenericFindDesktopToyMatch(Match const&, bool);
	virtual AlpoSprite* FindBuryToy(void);
	virtual AlpoSprite* FindChewToy(void);
	virtual AlpoSprite* FindPlayToy(void);
	virtual AlpoSprite* FindSweetKindToy(void);
	virtual AlpoSprite* FindGroomVanityToy(void);
	virtual AlpoSprite* FindChildToy(void);
	virtual AlpoSprite* FindSmallDesktopToy(void);
	virtual AlpoSprite* FindRomanticToy(void);
	virtual AlpoSprite* FindFetchToy(void);
	virtual AlpoSprite* FindRideableToy(void);
	virtual AlpoSprite* FindSharpenableToy(void);
	virtual AlpoSprite* FindSniffableToy(void);
	virtual AlpoSprite* FindAttackableToy(void);
	virtual AlpoSprite* FindTossToy(void);
	virtual AlpoSprite* FindTugToy(void);
	virtual AlpoSprite* FindFetchPartner(void);
	virtual AlpoSprite* FindTugPartner(void);
	virtual void DebugFindToy(void);
	virtual void InitTrickMemory(void);
	virtual void PrintTrickMemory(void);
	virtual void GetTrickToDo(AlpoSprite*, GestureType, AlpoSprite*, PetPlanName*, int*, int*);
	virtual TrickMemoryType* GetRandomNewTrickForThisGesture(GestureType);
	virtual void LearnTrick(bool);
	virtual int GetCurrentLearningRate(bool);
	virtual GestureType GetCurrentGesture(void);
	virtual void HandleRewarded(AlpoSprite*, AlpoSprite*, bool, bool);
	virtual void HandleDisciplined(AlpoSprite*, AlpoSprite*, bool);
	virtual void LearnByReinforcement(GoalToken&, bool, bool, bool);
	virtual int MapFromUNeutral(UNeutral);
	virtual void PushUAction(UAction);
	virtual int MapFromUAction(UAction);
	virtual void PushCatAction(int);
	virtual void PushDogAction(int);
	virtual void PushLayeredUAction(UAction, int, int);
	virtual void PushCatLayeredAction(int, int, int);
	virtual void PushDogLayeredAction(int, int, int);
	virtual int MapBreedSpecificAction(UAction) = 0;
	virtual bool IsThisADogLieDownNeutral(int);
	virtual void PetGetsTiredAndHungry(int, int);
	virtual AlpoSprite* FindSleepToy(pfvector<AlpoSprite*, char const*> const&);
	virtual bool CanISoundAdult(void) const;
	virtual void LoadPetBiorhythms(void);
	virtual void LoadLinezFileStuff(char const*);
	virtual void UpdateLinezFileStuff(void);
	virtual XTPoint<int> GetNosePointIfFacingForward(void);
	virtual XTPoint<int> GetBallPointAfterSimulation(int, int, int, int, XTPoint<int>, int);
	virtual int GetMyAdoptedPetIndex(bool) const;
	virtual bool GetIsEatableSizeObject(AlpoSprite*);
	virtual void FailSafe(void);
	virtual Goal const* GetActiveGoal(void);
	virtual void LoadPetzInfo(int);
	virtual void SavePetzInfo(bool);
	virtual bool SavePetToDisk(void) const;
	virtual void ResetPet(void);
	virtual void SwitchToNewEnvironment(void);
	virtual bool AmIAnAdultToYou(AlpoSprite*) const;
	virtual bool AmIAChildToYou(AlpoSprite*) const;
	virtual bool AmIOlderThanYou(AlpoSprite*) const;
	virtual bool AmIYoungerThanYou(AlpoSprite*) const;
	virtual bool AmIHostChar(void);
	virtual bool PutUtilityAtMouseHole(void);
	virtual bool AreAnyMiceOut(bool);
	virtual bool GetPointNearMouseHole(XTPoint<int>*);
	virtual AlpoSprite* GetHoardingSprite(void);
	virtual int DetermineDistance(XTPoint<int>, XTPoint<int>);
	virtual XTPoint<int> GetHaulToPoint(void);
	virtual bool InMySnubCone(AlpoSprite*);
	virtual void KnockRandomToyOffShelf(void);
	virtual void BumpNearbyToys(void);
	virtual AlpoSprite* GetCloseToy(AlpoSprite*);
	virtual XTSmartPtr<Ledge*> GetLedgeNearby(void);
	virtual void HandleLedgeHasMoved(Ledge const&);
	virtual int RemoveSpritesWeDontKnowAbout(pfvector<XTSmartPtr<AlpoSprite*>, char const*>&);
	virtual int RemoveRootedSprites(pfvector<XTSmartPtr<AlpoSprite*>, char const*>&);
	virtual bool GetOkToBeGrabbed(void);
	virtual void EZSetGeneGoalTrait(Genome&, BehaviorTrait, TraitLevel);
	virtual void EZSetGeneSpriteTrait(Genome&, EAdj, TraitLevel);
	virtual XTRect<int, long> GetSpriteDrawRectLog(AlpoSprite*, int);
	virtual XTPoint<int> GetSpriteDrawPointLog(AlpoSprite*, int);
	virtual void GetOffEdgePoint(CharacterSprite&, XTPoint<int>&) const;
	virtual void GetAnyOffEdgePoint(CharacterSprite&, XTPoint<int>&) const;
	virtual void ILoveYouMom(PetGoalName);
	virtual void DispatchEmotions(EmotionToken&) override;
	virtual void DispatchGoals(int, GoalToken&) override;
	virtual void DispatchPlans(PlanToken&) override;
	virtual pfvector<XBrain, char const*>& GetBiorhythms(void) override;
	virtual bool GetIsPetz() const override;
	virtual bool GetShouldIDoHorizon() const override;
	virtual bool GetMustIDoHorizon() const override;
	virtual bool GetShouldIDoFootprints() const override;
	virtual bool SetShouldIBeDeleted(bool) override;
	virtual void Draw(XTRect<int, long>*, XTRect<int, long>*, XDrawPort*, EStackDraw) override;
	virtual void DebugDump() override;
	virtual void ResetStack(ResetType a, int b) override;
	virtual int MapFromUBall(UBall uball) override;
	virtual long HandleCallbacks(CallbackType callbackType, long something) override;
	virtual bool GetIsDependent(void) const override;
	virtual bool GetIsBehindPetDoor(void) const override;
	virtual short GetClassID(void) const override;
	virtual void GenerateNewGoal(void) override;
	virtual bool MaybeAddPauseGoal(int) override;
	virtual void CleanUpAfterPreviousGoal(void) override;
	virtual void FilterGoal(int, int*, AlpoSprite*, AlpoSprite*) override;
	virtual int GetOverallEmotionValue(int) const override;
	virtual Personality* GetPersonality(void) const override;
	virtual char const* GetGoalStringName(int) const override;
	virtual char const* GetPlanStringName(int) const override;
	virtual char const* GetEmotionStringName(int) const override;
	virtual int GetMaxPetEmotionName(void) const override;
	virtual bool AreWeAsleep(void) const override;
	virtual void Dispatch(bool, bool) override;
	virtual void PlayFoleySound(EFoleySound sound, EFlavor flavor) override;
	virtual void RunClicks() override;
	virtual void RunUpdate() override;
	virtual ~PetSprite();
	void InitPetSprite(LoadInfo const&, EChrz, char*, char*, char*, bool, int);
	private:
		virtual void InitNewPetSprite(int);
};